### ISSUE TITLE
Assert issue when starting from negative value

### ISSUE THREAD

**Issue by vadrian89** [jpnurmi/flutter_spinbox#19]
Hello, 
First of, thank you for your package!

My issue is that whenever I increment to negative value to 0 (-1 -> 0/ -0.1 -> 0.0) I get this exception:
```
The following assertion was thrown while handling a gesture:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/ui/src/ui/text.dart:458:16
start != null && start >= -1
is not true
```

This is how I initialise the object:
```
SpinBox(
spacing: 0,
min: min,
max: max,
step: step,
value: value,
decimals: decimals,
onChanged: onChanged,
)
```

Example of how I use it:
```
_spinbox(
label: "Max stock",
min: -1,
value: _maxStock,
onChanged: (val) => context.read<ReportsGeneratorCubit>().updateStock(max: val),
),
```
The issue seem to happen if the field isn't focused.
Any ideea how I can solve it?

**Comment by jpnurmi** [comment]
I'm not able to reproduce the issue with a negative value. Could you help me to reproduce the issue? I would need a minimal reproducible example. Something standalone that I can actually run.

**Comment by vadrian89** [comment]
Hi, sorry for the late reply I forgot to answer. 
I've built my own Spinner widget for the purpose I needed at the time so I deleted the code the app.

**Comment by D4n4m1** [comment]
Hello, i have noticed the same issue. The Source Code where it happens is here, within **SpinBoxMixin** of the `base_spin_box.dart` file in the Function :

```
void _updateController(double oldValue, double newValue) {
  final text = _formatText(newValue);
  final selection = _controller.selection;
  final oldOffset = value.isNegative ? 1 : 0;
  final newOffset = _parseValue(text).isNegative ? 1 : 0;

  _controller.value = _controller.value.copyWith(
    text: text,
    selection: selection.copyWith(
      baseOffset: selection.baseOffset - oldOffset + newOffset, <--  have to be >=-1
      extentOffset: selection.extentOffset - oldOffset + newOffset, <-- have to be >=-1
    ),
  );
}
```

_"The initial selection is `TextSelection.collapsed(offset: -1)`."_  =>  `selection.baseOffset = -1`.
So, if the `value < 0` is negative, then `oldOffset = 1`, and if the `newValue = 0` so the `newOffset = 0`. summing it up, ends with `baseOffset = -2` and analog `extentOffset = -2`.

The fix would be, to check it. 

``` 
const TextRange({
    required this.start,
    required this.end,
  }) : assert(start >= -1),
       assert(end >= -1);
```
