### ISSUE TITLE
Ripple effect behind InputDecoration 

### ISSUE THREAD

**Issue by vitorhm** [jpnurmi/flutter_spinbox#21]
When I use the `SpinBox` with a `InputDecoration` and **fillColor**, the ripple effect on `IconButton` remains behind the decoration:

https://user-images.githubusercontent.com/13134788/110793262-2fc0e800-8253-11eb-83a7-60cff533d32c.mov

I managed to solve this by wrapping the `SpinGesture` on `SpinButton` widget with a `Material` widget with **transparent** color, because flutter uses the `Material` widget to do the splash and if you have something on top of that material, then the effects renders behind.

https://user-images.githubusercontent.com/13134788/110793253-2c2d6100-8253-11eb-9ac0-069660c16451.mov

Let me know if I can make a pull request with the changes, thanks

**Comment by jpnurmi** [comment]
> I managed to solve this by wrapping the SpinGesture on SpinButton widget with a Material widget with transparent color, because flutter uses the Material widget to do the splash and if you have something on top of that material, then the effects renders behind.

Sounds good.

> Let me know if I can make a pull request with the changes, thanks

Sure, it would be very much appreciated!
