### ISSUE TITLE
Option to Hide Increment/Decrement Buttons

### ISSUE THREAD

**Issue by cranst0n** [jpnurmi/flutter_spinbox#23]
Would you consider an option to to hide/remove the increment/decrement buttons?

**Comment by jpnurmi** [comment]
Sounds reasonable :+1:

**Comment by jpnurmi** [comment]
v0.4.1 with a `showButtons` property published: https://pub.dev/packages/flutter_spinbox/changelog#041---2021-04-18

**Comment by cranst0n** [comment]
Awesome! Thanks for the great library!
