### ISSUE TITLE
Option to use theme colour when not focused

### ISSUE THREAD

**Issue by ConcenTech** [jpnurmi/flutter_spinbox#26]
When the SpinBox is not focused the button colour defaults to grey, clicking inside the textfield will focus the widget and change the buttons colours to use the theme colours.
Is the a possibility of adding an option to always use theme colours when enabled?
unfocused
![Screenshot 2021-04-22 113546](https://user-images.githubusercontent.com/70274454/115700798-f950af80-a35e-11eb-881e-cc5b39569749.png)

focused
![Screenshot 2021-04-22 113442](https://user-images.githubusercontent.com/70274454/115700831-02da1780-a35f-11eb-9029-f1aa9023aca5.png)
![Screenshot 2021-04-22 113609](https://user-images.githubusercontent.com/70274454/115700833-0372ae00-a35f-11eb-8b52-ecf58ae0a6ee.png)

Thanks

**Comment by jpnurmi** [comment]
Hi, I just wanted to leave a comment that the proposal sounds good, but I've been busy with other things recently. Would this be something you could help with, perhaps?

**Comment by ConcenTech** [comment]
@jpnurmi 
No problem, I will look into it

**Comment by gerardo-m** [comment]
@jpnurmi I just wanted to use this option so I submitted a PR. #39
