### ISSUE TITLE
SpinBox children of a stateful widget do not update

### ISSUE THREAD

**Issue by TommasoAzz** [jpnurmi/flutter_spinbox#32]
Hello,
I'm currently trying this plugin since it looks good for my needs.

I have a parent StatefulWidget with two integer values, two callbacks for updating both of them and calling setState every time I increment or decrement the value but just the spinbox that is manipulated updates, the other one stays the same, while I'd expect both of them to update since I'm rebuilding the parent widget.

I'm currently using Flutter 2.2.3 (but it happened also in 2.2.2), flutter_spinbox 0.5.2 and I'm on Windows. To reproduce the issue, just create a new Flutter project and replace class `_MyHomePageState` with the following code:
```dart
class _MyHomePageState extends State<MyHomePage> {
  int _counter1 = 0;
  int _counter2 = 10;

  void _changeCounter1(final int newVal) {
    setState(() {
      _counter1 = newVal;
      _counter2 = newVal % 10;
    });
  }

  void _changeCounter2(final int newVal) {
    setState(() {
      _counter1 = newVal % 10;
      _counter2 = newVal;
    });
  }

  @override
  Widget build(BuildContext context) {
    print('rebuild with counter 1: $_counter1 and counter 2: $_counter2');
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SpinBox(
              step: 1,
              decimals: 0,
              onChanged: (val) => _changeCounter1(val.toInt()),
              value: _counter1.toDouble(),
              min: 0,
              max: 100,
            ),
            SpinBox(
              step: 1,
              decimals: 0,
              onChanged: (val) => _changeCounter2(val.toInt()),
              value: _counter2.toDouble(),
              min: 0,
              max: 100,
            ),
          ],
        ),
      ),
    );
  }
}
```

The two values, `_counter1` and `_counter2` update, the spinboxes don't.

The example is super dummy, I do not care which value actually are present in the spinbox right now, I want just them to update.

I'd really appreciate to understand what is the problem, if I'm doing something wrong or what. Thanks!

**Comment by jpnurmi** [comment]
Not much details because I'm answering from phone, but try adding keys for the SpinBoxes.

**Comment by TommasoAzz** [comment]
It actually solved the issue (using `UniqueKey()`. Thank you so much!
