### ISSUE TITLE
Text not centered horizontally

### ISSUE THREAD

**Issue by rodi189** [jpnurmi/flutter_spinbox#36]
When use border property to remove bottom border for styleline purpose text of input is move to left

**Comment by rodi189** [comment]
I need to use the widget like this whitout bottom border and use the custom border of my container:
![Captura de pantalla de 2021-11-07 20-23-35](https://user-images.githubusercontent.com/5454762/140674639-b03d98d3-b349-4170-a4ac-ba0981f08c11.png)

**Comment by rodi189** [comment]
Current code i use to this:
`Container(
              margin: EdgeInsets.only(right: 50),
              decoration: BoxDecoration(
                  border: Border.all(color: colorBorde),
                  borderRadius: BorderRadius.circular(4)),
              child: SpinBox(
                textAlign: TextAlign.center,
                decoration: InputDecoration(
                  alignLabelWithHint: true,
                  border: OutlineInputBorder(borderSide: BorderSide.none),
                ),
              )),`

**Comment by jpnurmi** [comment]
| Normal | Guides |
|---|---|
| ![Screenshot from 2022-04-24 20-47-53](https://user-images.githubusercontent.com/140617/164991748-946912fa-4b6d-42cf-b092-9cc27d2d2da3.png) | ![Screenshot from 2022-04-24 20-48-18](https://user-images.githubusercontent.com/140617/164991746-5bde5e70-1934-45c4-9f61-7cae305ebe7e.png) |
