### ISSUE TITLE
The question is how can I detect multi-tap in a short period of time?

### ISSUE THREAD

**Issue by kvadrakot** [jpnurmi/flutter_spinbox#38]
I would like to thank you for the spinbox, it is beautiful.  I have a question. I use a widget on the product page to specify how many products to put in the cart. After increasing the counter, there is a http request for a remote api, but if the user taps quickly (on IncrementIcon/DecrementIcon), then it will be too many requests to the remote server. How can I add a callback that will be triggered on multiple taps, such as in GestureDetector (onDoubleTap),  or some other way of determining that the user has taped many times in a row and get the last value where the user stoped.

**Comment by jpnurmi** [comment]
I'm afraid this is something that would be better handled on the application side, not in a general-purpose widget. Typically, there would be a view model that handles such business logic, as scheduling service calls, between the view and the service.
