### ISSUE TITLE
AddListener not removed

### ISSUE THREAD

**Issue by leonardo2204** [jpnurmi/flutter_spinbox#44]
Hey, @jpnurmi, hope you are ok! 
After submitting my PR yesterday I noticed that you add listener to focusScope but you never remove them. Can it cause a leak?
https://github.com/jpnurmi/flutter_spinbox/blob/main/lib/src/base_spin_box.dart#L76

I'm not sure if just calling dispose() would suffice, but if not, we should probably remove those listeners, right?

Thanks and see ya!

**Comment by jpnurmi** [comment]
I think it's not strictly necessary because after `dispose()`, because a call to `notifyListeners()` or any other `ChangeNotifier` methods would throw. I guess it wouldn't hurt to explicitly remove the listener, but the listeners are never accessed after `dispose()` anyway.
