### ISSUE TITLE
Error: Method not found: 'Object.hash'.

### ISSUE THREAD

**Issue by fabioselau077** [jpnurmi/flutter_spinbox#46]
Launching lib/main_dev.dart on Redmi 8 in debug mode...
lib/main_dev.dart:1
: Error: Method not found: 'Object.hash'.
../…/material/spin_box_theme.dart:46
  int get hashCode => Object.hash(iconColor, decoration);
                             ^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script '/home/fabio/fvm/versions/stable/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/fabio/fvm/versions/stable/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by jpnurmi** [comment]
Try upgrading to Flutter 2.5 or later that comes with Dart 2.14.
