### ISSUE TITLE
CupertinoSpinBox initialValue not resetting

### ISSUE THREAD

**Issue by soccerjf** [jpnurmi/flutter_spinbox#7]
Good day, I'm using 2 cupertinospinboxs. Both allow for individual "spins".  When the 1st spinner is set to 0 (zero), the 2nd widget is expected to be reset to 0 as well.  The underlaying data source is managed by Provider and ChangeNotifier.  I console print out the value of initialValue for both spinners and see that the initial build is correct for both initialValues. When the 1st spinner is set to 0, the console print shows the 2nd spinner's initialValue is the expected 0 value but the displayed value remains at the current value, ie not getting reset.
Not sure if this is an issue specific to your script so Im still researching for a solution but was hoping you may have a solution/correction or workaround.
Thank you for your time.

**Comment by jpnurmi** [comment]
Could you help me to understand the problem by providing a short example snippet that illustrates the problem?

**Comment by soccerjf** [comment]
Thxs for getting back to me.  Hopefully below I’ve shown you what the issue is.



Initial value is properly set to “1"



Console log of the print statement showing the initalValue given to the spin box correctly, which is 1



Then when the spin box associated with the column “Caution” is set to zero (0) the initialValue for spin box under column “Time” should be 0 as well.  The value being based to the “Time” spin box is 0, as shown in the console log below, but the screen/UI never refreshes with the new value past to it.

**Comment by soccerjf** [comment]
Found a solution.  I added the Key parameter with a UniqueKey, to the widget holding the spinbox.  Now when the value is reset in the other widget, the results are as expected.

**Comment by jpnurmi** [comment]
I'll take it that the problem was solved. Let me know if you think there's something that should be changed in `flutter_spinbox`.
